### ISSUE TITLE
AiScriptでMisskeyクライアントプラグインを作れる機能

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6443]
## Summary

投稿フォーム、投稿メニュー、ユーザーメニューなどの様々な箇所に新たなアイテムを追加できるAPIや、投稿フォームを開くAPI、投稿時にフックして内容を編集したりできるAPIなどを用意してAiScriptでプラグインを作れるようにする

## TODO
- [x] 投稿フォームにアクション(ボタン)を追加するAPI
- [x] 投稿メニューにアクション(ボタン)を追加するAPI
- [x] ユーザーメニューにアクション(ボタン)を追加するAPI
- [ ] ドライブメニューにアクション(ボタン)を追加するAPI
- [ ] 投稿フォームを開くAPI
- [ ] 投稿時フック
- [x] クライアント起動時フック
- [ ] タイムラインのストリームでノート受信した時フック
- [ ] ↑で受信した投稿プロパティ書き換えフック
- [ ] ページ遷移API
  - 外部URLに飛べるようにすると、セキュリティリスクになるので要検討
- [ ] ポップアップメニュー表示API
- [x] インストール/アンインストール時に再起動
- [x] 設定情報がエクスポートされていればform-windowコンポーネントを使ってプラグインの設定を行えるようにする
  - [x] ↑で設定した設定情報を取得するAiScriptAPIを用意する
- [x] 権限を指定してユーザーのアクセストークンを取得するAPI

**Comment by syuilo** [comment]
> AIScript API プラグイン、権限を求めるようにしたほうが良さそうだね　どういう所に作用するのかユーザーが知っていないとアレだし

**Comment by syuilo** [comment]
プラグインのメタ情報をどう持たせるかだな

**Comment by syuilo** [comment]
AiScript内にプラグイン情報オブジェクトを持たせるか、package.jsonのようなファイルを同梱させるか

**Comment by syuilo** [comment]
JSONのAiScript表記バージョン作ってそれで書かせるか

**Comment by syuilo** [comment]
ISON

**Comment by syuilo** [comment]
とりあえず meta.json で

**Comment by syuilo** [comment]
meta.json
main.is

**Comment by syuilo** [comment]
あーでもそうするとクライアントサイドでzip解析とかしないといけなくて面倒だな

**Comment by syuilo** [comment]
プラグイン設定UIはHPMLでいいかな

**Comment by syuilo** [comment]
そうなるとHPMLが使われるのはPagesに限らなくなるから、名前をMUML(Misskey Ui Markup Language)とかにした方が良いかもしれない

**Comment by syuilo** [comment]
単に設定情報もらってレンダリングすれば良さそう
