### ISSUE TITLE
External logins and url fields

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#66]
プロフィールの左側にTwitterと連携するとTwitterアカウントへのリンクが表示されるのと同じようにGitHubとFoursquareと連携する機能が欲しいです
あとブログへのリンクを貼りたいのでURL欄も欲しいです

# Tasks

- auth
  - [x] GitHub auth (Done in #3095)
  - [ ] Foursquare auth
  - [x] Discord auth (Done in #3239)
  - [ ] Mastodon auth
  - [ ] (Other instance of) Misskey auth
- [x] URL frames

**Comment by acid-chicken** [comment]
# Tasks

- auth
  - [ ] GitHub auth
  - [ ] Foursquare auth
- [ ] URL frames

**Comment by incognico** [comment]
Can we hide the "Log in with Twitter" link completely in the login dialog if config.twitter is empty? Same with gh and 4[] then.

**Comment by tamaina** [comment]
@acid-chicken がサブトラッカーにしてるけど名前変えませんか？

**Comment by tamaina** [comment]
URL framesは別のissueにしたほうがよさそう

**Comment by 4ioskd** [comment]
V11時代の残存issueと思われるため、閉じても良いかと思います。また、GithubやDiscord以外の外部サービスによるログイン認証の選択肢をこれ以上増やすと、それらへの対応やメンテナンス面でも負担がかかるでしょう。外部サービスによるログイン認証自体の是非については、またの機会に別のissueとして取り上げたい。

**Comment by tamaina** [comment]
v11とかそんな最近じゃなくて相当古いわよこれ
